### ISSUE TITLE
"no running event loop" on ComfyUI v0.2.3

### ISSUE THREAD

**Issue by joshcreter** [AustinMroz/ComfyUI-WorkflowCheckpointing#4]
Recent changes to ComfyUI have broken this extension.

It now fails to load with the following error?

> Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-WorkflowCheckpointing module for custom nodes: no running event loop

Could you please look into this? I really, really want to be able to use it again.

**Comment by AustinMroz** [comment]
While I haven't had the time to finish my rewrite that properly integrates things with the execution cache, I had also written (but forgotten to push) a set of minimal changes that restores functionality with newer versions of ComfyUI.

These changes have now been pushed to both master, and the publish branch which the Comfy Registry tracks from.

**Comment by joshcreter** [comment]
Thank you – I'll give it a test and let you know if I have any major issues

Looking forward to the rewrite! I don't have deep knowledge of ComfyUI internals otherwise I'd try to help out. But I will test it as soon as it's done
